import type { QualityTier, VideoModel } from "@/types/generation.types";

const TIER_ORDER: Record<QualityTier, number> = {
  economy: 0,
  balanced: 1,
  premium: 2,
};

const SEEDANCE_ASPECT_RATIOS = ["16:9", "9:16", "1:1", "4:3", "21:9"] as const;
const FAL_ASPECT_RATIOS = ["16:9", "9:16", "1:1"] as const;
const SEEDANCE_RESOLUTIONS = ["480p", "720p", "1080p"] as const;

const UNSORTED_VIDEO_MODELS: VideoModel[] = [
  {
    id: "wan-2.5-480p-text-to-video",
    label: "Wan 2.5 480p Text-to-Video",
    provider: "fal",
    endpoint: "fal-ai/wan-25-preview/text-to-video",
    description: "Modelo economico para iteracion rapida y generacion masiva.",
    modes: ["text-to-video"],
    durations: [5, 10],
    resolutions: ["480p"],
    aspectRatios: [...FAL_ASPECT_RATIOS],
    qualityTier: "economy",
    supportsAudio: false,
    supportsReferenceImage: false,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.05 },
    pricingDescription: "$0.05/s",
  },
  {
    id: "ovi-image-to-video",
    label: "Ovi Image-to-Video",
    provider: "fal",
    endpoint: "fal-ai/ovi/image-to-video",
    description: "Modelo ultra barato para image-to-video con audio.",
    modes: ["image-to-video"],
    durations: [5],
    resolutions: ["auto"],
    aspectRatios: [...FAL_ASPECT_RATIOS],
    qualityTier: "economy",
    supportsAudio: true,
    supportsReferenceImage: true,
    supportsTextPrompt: true,
    pricing: { type: "per_video", pricePerVideoUsd: 0.2 },
    pricingDescription: "$0.20/video",
  },
  {
    id: "wan-2.5-720p-text-to-video",
    label: "Wan 2.5 720p Text-to-Video",
    provider: "fal",
    endpoint: "fal-ai/wan-25-preview/text-to-video",
    description: "Modelo equilibrado para videos de calidad media a bajo coste.",
    modes: ["text-to-video"],
    durations: [5, 10],
    resolutions: ["720p"],
    aspectRatios: [...FAL_ASPECT_RATIOS],
    qualityTier: "balanced",
    supportsAudio: false,
    supportsReferenceImage: false,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.1 },
    pricingDescription: "$0.10/s",
  },
  {
    id: "wan-2.5-1080p-text-to-video",
    label: "Wan 2.5 1080p Text-to-Video",
    provider: "fal",
    endpoint: "fal-ai/wan-25-preview/text-to-video",
    description: "Modelo 1080p mas barato que Seedance para renders de mas calidad.",
    modes: ["text-to-video"],
    durations: [5, 10],
    resolutions: ["1080p"],
    aspectRatios: [...FAL_ASPECT_RATIOS],
    qualityTier: "balanced",
    supportsAudio: false,
    supportsReferenceImage: false,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.15 },
    pricingDescription: "$0.15/s",
  },
  {
    id: "kling-2.5-turbo-pro-image-to-video",
    label: "Kling 2.5 Turbo Pro Image-to-Video",
    provider: "fal",
    endpoint: "fal-ai/kling-video/v2.5-turbo/pro/image-to-video",
    description: "Buena opcion calidad/precio para animar imagenes.",
    modes: ["image-to-video"],
    durations: [5, 10],
    resolutions: ["720p", "1080p"],
    aspectRatios: [...FAL_ASPECT_RATIOS],
    qualityTier: "balanced",
    supportsAudio: false,
    supportsReferenceImage: true,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.07 },
    pricingDescription: "$0.07/s",
  },
  {
    id: "seedance-2.0-fast-text-to-video",
    label: "Seedance 2.0 Fast Text-to-Video",
    provider: "seedance",
    endpoint: "/v1/video/generations",
    description: "Seedance Fast para renders finales con mejor calidad.",
    modes: ["text-to-video"],
    durations: [5, 10],
    resolutions: [...SEEDANCE_RESOLUTIONS],
    aspectRatios: [...SEEDANCE_ASPECT_RATIOS],
    qualityTier: "premium",
    supportsAudio: true,
    supportsReferenceImage: false,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.2419 },
    pricingDescription: "$0.2419/s",
  },
  {
    id: "seedance-2.0-fast-image-to-video",
    label: "Seedance 2.0 Fast Image-to-Video",
    provider: "seedance",
    endpoint: "/v1/video/generations",
    description: "Seedance Fast desde imagen de referencia.",
    modes: ["image-to-video"],
    durations: [5, 10],
    resolutions: [...SEEDANCE_RESOLUTIONS],
    aspectRatios: [...SEEDANCE_ASPECT_RATIOS],
    qualityTier: "premium",
    supportsAudio: true,
    supportsReferenceImage: true,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.2419 },
    pricingDescription: "$0.2419/s",
  },
  {
    id: "seedance-2.0-fast-reference-to-video",
    label: "Seedance 2.0 Fast Reference-to-Video",
    provider: "seedance",
    endpoint: "/v1/video/generations",
    description: "Seedance Fast multimodal con referencias.",
    modes: ["reference-to-video"],
    durations: [5, 10],
    resolutions: [...SEEDANCE_RESOLUTIONS],
    aspectRatios: [...SEEDANCE_ASPECT_RATIOS],
    qualityTier: "premium",
    supportsAudio: true,
    supportsReferenceImage: true,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.2419 },
    pricingDescription: "$0.2419/s",
  },
  {
    id: "seedance-2.0-text-to-video",
    label: "Seedance 2.0 Text-to-Video",
    provider: "seedance",
    endpoint: "/v1/video/generations",
    description: "Seedance estandar para maxima calidad.",
    modes: ["text-to-video"],
    durations: [5, 10],
    resolutions: [...SEEDANCE_RESOLUTIONS],
    aspectRatios: [...SEEDANCE_ASPECT_RATIOS],
    qualityTier: "premium",
    supportsAudio: true,
    supportsReferenceImage: false,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.3034 },
    pricingDescription: "$0.3034/s",
  },
  {
    id: "seedance-2.0-image-to-video",
    label: "Seedance 2.0 Image-to-Video",
    provider: "seedance",
    endpoint: "/v1/video/generations",
    description: "Seedance estandar desde imagen.",
    modes: ["image-to-video"],
    durations: [5, 10],
    resolutions: [...SEEDANCE_RESOLUTIONS],
    aspectRatios: [...SEEDANCE_ASPECT_RATIOS],
    qualityTier: "premium",
    supportsAudio: true,
    supportsReferenceImage: true,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.3034 },
    pricingDescription: "$0.3034/s",
  },
  {
    id: "seedance-2.0-reference-to-video",
    label: "Seedance 2.0 Reference-to-Video",
    provider: "seedance",
    endpoint: "/v1/video/generations",
    description: "Seedance estandar multimodal con referencias.",
    modes: ["reference-to-video"],
    durations: [5, 10],
    resolutions: [...SEEDANCE_RESOLUTIONS],
    aspectRatios: [...SEEDANCE_ASPECT_RATIOS],
    qualityTier: "premium",
    supportsAudio: true,
    supportsReferenceImage: true,
    supportsTextPrompt: true,
    pricing: { type: "per_second", pricePerSecondUsd: 0.3034 },
    pricingDescription: "$0.3034/s",
  },
];

export const VIDEO_MODELS = [...UNSORTED_VIDEO_MODELS].sort(
  (left, right) => TIER_ORDER[left.qualityTier] - TIER_ORDER[right.qualityTier],
);

export const DEFAULT_MODEL = VIDEO_MODELS[0];
